version: '3.8'

services:
  bot:
    build: .
    container_name: trading-bot
    command: python main.py
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ -f /app/data/health/heartbeat ] && [ $$(($$(date +%s) - $$(cat /app/data/health/heartbeat))) -lt 180 ]"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build: .
    container_name: trading-dashboard
    command: python -m src.ui.dashboard --mode web --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - bot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/data"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
